/*
 * This utility takes two major arguments: the name of a sheetset file and the name of a pdf output file.
 * We plot the complete sheetset to the pdf file, using the first entry in the sheetset's list of page setup overrides.
 * 
 * 
 * Internally, the strategy is to read the sheetset file to construct an AutoCAD sheet list file (a *.dsd file, which seems to use the ini format.),
 * and then use the Document.SendCommand function of the Auotcad COM API to send a "-PUBLISH" command to the Autocad shell, along with the path
 * of our newly-constructed dsd file.
 * The Autocad documentation recommends against manually constructing a dsd file, saying that the better way to do it is use the AutoCAD API,
 * because the format of the dsd file is liable to change between versions of AutoCAD.
 * However, the part of the Autocad API that supports generating a dsd file (The AcadApplication.Publisher namespace (or something like that)) is not exposed via COM, 
 * but is only exposed via the ObjectArx API.
 * This means that if we want to use the API to construct the dsd file, we have to deal with the rigamarole of telling AutoCAD, via COM, to load
 * an OBjectARX dll, which we have to create to do the desired constructing of the dsd file.  This seems to me to be more trouble than it is worth -
 * I can imagine that I would have to invent some non-standard, probably buggy, way to communicate with the loaded ObjectARX dll to tell it
 * What files to put in the dsd file.  There may be some way to do this, but I do not have a clear idea of how at the moment.  The most
 * intuitive approach, to my mind, is to construct the dsd file myself.  The dsd format seems to be understandable by glancing at a few examples of dsd 
 * files generated by the Autocad PUBLISH command.
 * 
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Autodesk.AutoCAD.Interop;
using Autodesk.AutoCAD.Interop.Common;
using ACSMCOMPONENTS23Lib;
using System.Runtime.InteropServices;

namespace acad_sheetset_to_pdf
{

    class Program
    {
        //The [STAThread] statement below was the answer to make the instatntiation of the COM objects stop complaining that the interface could not be found.
        [STAThread] 
        static void Main(string[] args)
        {
            String nameOfDwgFileContainingThePageSetup;
            String nameOfThePageSetup;
            
            //*****parse the command-line arguments*****
            //for now, I will simply hard code these values.
            String nameOfSheetsetFile = "C:\\work\\ec-18-013_les_schwab_397\\main_sheet_set.dst";
            String nameOfPdfOutputFile = "C:\\work\\ec-18-013_les_schwab_397\\out.pdf";
            //TO DO: parse and verify the real command-line arguments, compose a help message.

            //*****read the sheetset file and construct a dsd file accordingly*****
            IAcSmSheetSetMgr sheetSetMgr;
            IAcSmDatabase sheetdb;
            IAcSmSheetSet sheetSet;

            sheetSetMgr = new AcSmSheetSetMgr();
 
            Console.WriteLine("attempting to open " + nameOfSheetsetFile);
            sheetdb = sheetSetMgr.OpenDatabase(nameOfSheetsetFile, bFailIfAlreadyOpen: false);
            if (sheetdb.GetLockStatus() == 0) { sheetdb.LockDb(sheetdb); } //it may not be necessary to lock the sheetset, because I am only reading from it, not writing to it.
            sheetSet = sheetdb.GetSheetSet();
            if (sheetdb.GetLockStatus() != 0) { sheetdb.UnlockDb(sheetdb); }
            //read the page setup override information from the sheet set.

            //IAcSmNamedAcDbObjectReference myNamedAcDbObjectReference;
            //myNamedAcDbObjectReference = sheetSet.GetDefAltPageSetup();

            nameOfDwgFileContainingThePageSetup = sheetSet.GetAltPageSetups().ResolveFileName();

            //nameOfThePageSetup = sheetSet.GetDefAltPageSetup().GetName();
            // the above is not working because sheetSet.GetDefAltPageSetup() returns null.
            // I suspect that sheetSet.GetDefAltPageSetup() only returns something when
            // this code is being run within the Autocad process.
            //as a work-around, we might have to open the dwg file containing the page setup, and read out the page setup names from it.
            nameOfThePageSetup = "ahoy";

            Console.WriteLine("nameOfDwgFileContainingThePageSetup: " + nameOfDwgFileContainingThePageSetup);
            Console.WriteLine("nameOfThePageSetup: " + nameOfThePageSetup);
            

            IAcSmEnumComponent myAcSmEnumComponent = sheetSet.GetSheetEnumerator();
            IAcSmComponent thisAcSmComponent;
            IAcSmSheet thisSheet;
            while ((thisAcSmComponent = myAcSmEnumComponent.Next()) != null)
            {
                Console.WriteLine(thisAcSmComponent.GetObjectId().GetPersistObject().GetTypeName());
                thisSheet = (IAcSmSheet) thisAcSmComponent.GetObjectId().GetPersistObject();
                Console.WriteLine("thisSheet.GetName(): " + thisSheet.GetName());		//                 thisSheet.GetName()
                Console.WriteLine("thisSheet.GetLayout().GetName(): " + thisSheet.GetLayout().GetName());		//                 thisSheet.GetLayout().GetName()
            }

            if (sheetdb.GetLockStatus() != 0){ sheetdb.UnlockDb(sheetdb);}

            // Keep the console window open
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
    }
}
